// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv4xHB5O8dInPPwnMZDvj2T0-U6f_v6bw',
    appId: '1:472906797023:web:577fa7ef3fda15f10e7e6a',
    messagingSenderId: '472906797023',
    projectId: 'arsns-dcb2c',
    authDomain: 'arsns-dcb2c.firebaseapp.com',
    storageBucket: 'arsns-dcb2c.firebasestorage.app',
    measurementId: 'G-70PGHMGKQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLCbPzyGRqOIZCZi-XxN-IcWOKjqMStpo',
    appId: '1:472906797023:android:143b0dd869ae7fda0e7e6a',
    messagingSenderId: '472906797023',
    projectId: 'arsns-dcb2c',
    storageBucket: 'arsns-dcb2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEjnbkhZfFIkw4KYD0oUoXiWg7J83cOEE',
    appId: '1:472906797023:ios:8c345eda0a68e6330e7e6a',
    messagingSenderId: '472906797023',
    projectId: 'arsns-dcb2c',
    storageBucket: 'arsns-dcb2c.firebasestorage.app',
    iosBundleId: 'com.example.arSnsFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEjnbkhZfFIkw4KYD0oUoXiWg7J83cOEE',
    appId: '1:472906797023:ios:8c345eda0a68e6330e7e6a',
    messagingSenderId: '472906797023',
    projectId: 'arsns-dcb2c',
    storageBucket: 'arsns-dcb2c.firebasestorage.app',
    iosBundleId: 'com.example.arSnsFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv4xHB5O8dInPPwnMZDvj2T0-U6f_v6bw',
    appId: '1:472906797023:web:411fa09aeb2972630e7e6a',
    messagingSenderId: '472906797023',
    projectId: 'arsns-dcb2c',
    authDomain: 'arsns-dcb2c.firebaseapp.com',
    storageBucket: 'arsns-dcb2c.firebasestorage.app',
    measurementId: 'G-B1NN8W5B0G',
  );
}
